version: '3.3'

services: 
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql
      - ./cadastro.sql:/docker-entrypoint-initdb.d/cadastro.sql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABSE=cadastro

  app:
    image: phpmyadmin/phpmyadmin:4.8.2
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    
  application:
    build: . 
    command: "npm run dev"
    ports:
      - "80:8080"
    volumes:
      - ./.:/app
      - ./node_modules:/app/node_modules  
  gulp:
    build: .
    depends_on: 
      - application
    command: "npm run gulp"
    volumes:
      - ./.:/app
      - ./node_modules:/app/node_modules
volumes:
  db_data: